### ISSUE TITLE
getItems 获取到空数组

### ISSUE THREAD

**Issue by clddup** [alexzhang1030/to-path-tree#43]
按照例子
```js
import { PathTreeBuilder } from 'to-path-tree'

const builder = new PathTreeBuilder()
builder.addPath('src/index.ts')
builder.addPath('src/a/index.ts')
builder.removePath('src/index.ts')
console.log(builder.getItems('src/a/'))
```
结果打印空数组 []

**Comment by alexzhang1030** [comment]
closed by e84e7dff1e2159f73f98d425c4d82e137342b64d, 你可以升级到 `v1.2.0`.

需要注意的一点是：
- `getItems` 只能拿到当前路径下的文件地址
- 如果需要获取子目录，可以使用 `getSubDirectories`

如果有任何建议可以开新的 issue, 或者 pr 可以很欢迎的。

**Comment by clddup** [comment]
你这晚上不休息啊? 当代铁人 大佬

**Comment by alexzhang1030** [comment]
> 你这晚上不休息啊? 当代铁人 大佬

刚好看到了~

**Comment by clddup** [comment]
我想传入path, 不获取子文件, 子目录, 而是获取当前传入path这一项
